name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: 設定 Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        
    - name: 安裝依賴
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: 執行測試
      run: |
        python -m pytest tests/
        
    - name: 建立執行檔
      run: |
        pyinstaller --onefile src/main.py
        
    - name: 上傳構建產物
      uses: actions/upload-artifact@v3
      with:
        name: app-build
        path: dist/

  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: 下載構建產物
      uses: actions/download-artifact@v3
      with:
        name: app-build
        
    - name: 建立發布
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          app-build/* 